Make the debug build link again
The (non-optimized) build fails with:

  | /usr/bin/ld: CMakeFiles/rpg.dir/M2optPolyII.c.o: in function `collinearitiesResolved':
  | M2optPolyII.c:(.text+0x793): undefined reference to `incrIndex'

since a function was only given in an 'inline void' variant without any
non-inline alternative.

Dropped the unneeded inline.